language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - pypy
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=ant setup.py test
  - python setup.py install
  - antfs-cli --help
after_success:
  - coveralls
